### Test Image Upload (Ingestion)
POST http://localhost:8000/upload/
Content-Type: multipart/form-data; boundary=boundary

--boundary
Content-Disposition: form-data; name="file"; filename="test_image.jpg"
Content-Type: image/jpeg

< ./test_image.jpg
--boundary--

### Test Folder Scan (Batch Ingestion)
POST http://localhost:8000/scan-folder/
#POST https://api-service-route-beny20-dev.apps.rm2.thpm.p1.openshiftapps.com/scan-folder/
Accept: application/json

### ----------------------------------------------------

GET http://localhost:9200/writers_index/_search
Content-Type: application/json

{
  "query": {
    "match_all": {}
  }
}