version: '3.8'

services:

  kafka:
    image: confluentinc/cp-kafka:7.8.3
    container_name: kafka
    user: root
    ports:
      - "9092:9092"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_LISTENERS: INTERNAL://0.0.0.0:29092,EXTERNAL://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka:29092,EXTERNAL://localhost:9092
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_LOG_DIRS: /var/lib/kafka/data
      CLUSTER_ID: MkU3OEVBNTcwNTJENDM2Qk
    volumes:
      - ./data/kafka-confluent:/var/lib/kafka/data
    networks:
      - reshet_net
    healthcheck:
      test: ["CMD-SHELL", "kafka-broker-api-versions --bootstrap-server localhost:9092"]
      interval: 10s
      timeout: 5s
      retries: 5

  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - ./data/mongo:/data/db
    networks:
      - reshet_net
    healthcheck:
      test: ["CMD-SHELL", "mongosh --quiet --eval \"db.adminCommand('ping').ok\""]
      interval: 10s
      timeout: 5s
      retries: 5

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.10.4
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - ES_JAVA_OPTS=-Xms1g -Xmx1g
    ports:
      - "9200:9200"
    volumes:
      - ./data/es_data:/usr/share/elasticsearch/data
    networks:
      - reshet_net
    healthcheck:
      test: ["CMD-SHELL", "curl -s http://localhost:9200/_cluster/health | grep -qE '\"status\":\"(green|yellow)\"'"]
      interval: 10s
      timeout: 5s
      retries: 5

  api-service:
    build:
      context: .
      dockerfile: API_app/Dockerfile
    container_name: api-service
    ports:
      - "8000:8000"
    environment:
      - MONGO_URI=mongodb://mongo:27017/
      - KAFKA_BROKER=kafka:29092
      - KAFKA_TOPIC=FILE_UPLOADED
      - INPUT_FOLDER=/app/input_images
    volumes:
      - ./API_app/input_images:/app/input_images
    depends_on:
      mongo:
        condition: service_healthy
      kafka:
        condition: service_healthy
    networks:
      - reshet_net

  ocr-service:
    build:
      context: .
      dockerfile: OCREngine/Dockerfile
    container_name: ocr-service
    environment:
      - MONGO_URI=mongodb://mongo:27017/
      - KAFKA_BROKER=kafka:29092
      - CONSUME_TOPIC=FILE_UPLOADED
      - PRODUCE_TOPIC=RAW_TEXT_EXTRACTED
      - GROUP_ID=ocr_group
    depends_on:
      mongo:
        condition: service_healthy
      kafka:
        condition: service_healthy
    networks:
      - reshet_net

  clean-service:
    build:
      context: .
      dockerfile: CleanService/Dockerfile
    container_name: clean-service
    environment:
      - MONGO_URI=mongodb://mongo:27017/
      - KAFKA_BROKER=kafka:29092
      - CONSUME_TOPIC=RAW_TEXT_EXTRACTED
      - PRODUCE_TOPIC=TEXT_CLEANED
      - GROUP_ID=clean_group
    depends_on:
      mongo:
        condition: service_healthy
      kafka:
        condition: service_healthy
    networks:
      - reshet_net

networks:
  reshet_net:
    driver: bridge
